/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Abalon;

public class App {
    public char getGreeting() {
    	return 'B' - 1;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
